
#ifndef __SIMULATION_3D__DEFINITIONS_H__
#define __SIMULATION_3D__DEFINITIONS_H__


#ifndef S3D_DEFAULT_COLOUR_RED
#define S3D_DEFAULT_COLOUR_RED 1.0 
#endif

#ifndef S3D_DEFAULT_COLOUR_GREEN
#define S3D_DEFAULT_COLOUR_GREEN 1.0
#endif

#ifndef S3D_DEFAULT_COLOUR_BLUE
#define S3D_DEFAULT_COLOUR_BLUE 1.0
#endif

#ifndef S3D_DEFAULT_COLOUR_OPAC
#define S3D_DEFAULT_COLOUR_OPAC 1.0
#endif

#ifndef S3D_DEfAULT_COLOUR
#define S3D_DEFAULT_COLOUR S3D::colour( S3D_DEFAULT_COLOUR_RED, S3D_DEFAULT_COLOUR_GREEN, S3D_DEFAULT_COLOUR_BLUE, S3D_DEFAULT_COLOUR_OPAC )
#endif


#endif // __SIMULATION_3D__DEFINITIONS_H__

